<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Enter your query_vfb-23</name>
   <tag></tag>
   <elementGuidId>ad9dd7a5-3d19-48b5-a8e2-9e9742dc4935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='vfb-23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>992fd243-0d63-4d32-8dd1-9696a5a9dba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-23</value>
      <webElementGuid>3623dd36-55cf-4647-a863-ce8474d6d08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-23</value>
      <webElementGuid>c6fbb309-c8f9-4a98-9618-e892ccd1999e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-textarea  vfb-medium  </value>
      <webElementGuid>46cfd542-5673-4123-b2a3-0218919e549c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-23&quot;)</value>
      <webElementGuid>e73e64ec-bb0b-48f7-b9bf-e96bf74ee524</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='vfb-23']</value>
      <webElementGuid>49ef413e-9293-44e6-946d-29d0535383de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-23']/div/textarea</value>
      <webElementGuid>88ea1e2b-0128-4643-b874-1085b0a7135c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>79ee6672-49d4-46ae-b9f3-2e3e03ff5ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'vfb-23' and @id = 'vfb-23']</value>
      <webElementGuid>b2fbd608-6996-4c4e-8e0c-4c50fab776fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
